[package]
name = "cock-lib"
version = "1.0.0"
edition.workspace = true
authors.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive.workspace = true
